In [4]:
import numpy as np
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])


In [2]:
# real value of v
v = np.array([3,5,-1,4])

In [152]:
# alt value for v to test code
v = np.array([5,6,7,9,-2])

In [5]:
# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape 
}

dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

In [27]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

### Vector addition, subtraction, & multiplication

We could write a list comprehension:
    
    u_plus_v =  [u[i]+v[i] for i in range(len(u))] if len(u) == len(v)

but this is overly verbose.

Instead, we can take advantage of numpy's array addition:

In [74]:
u, v

(array([ 6,  2, -3,  5]), array([ 3,  5, -1,  4]))

In [77]:
#u_plus_v = 
[u+v] if len(u) == len(v) else None

[array([ 9,  7, -4,  9])]

In [78]:
[u+v]

[array([ 9,  7, -4,  9])]

In [79]:
u+v

array([ 9,  7, -4,  9])

The same applies to subtraction

In [82]:
#u_minus_v = 
[u-v] if len(u) == len(v) else None           # u-v

[array([ 3, -3, -2,  1])]

In [81]:
u-v

array([ 3, -3, -2,  1])

In [ ]:
#alpha_times_u = 

again, list comprehension is overly verbose:

    alpha_times_u =  [alpha*x for x in u]     

We can take advantage of numpy's array multiplication instead:

In [80]:
alpha*u     # alpha * u, alpha = 6

array([ 36,  12, -18,  30])

### Vector dot products

numpy has a 'dot' method:

    u_dot_v = np.dot(u,v)

but we need to assign 'None' if dot product is undefined

In [ ]:
u_dot_v = sum([u[i]*v[i] for i in range(len(u))]) if len(u) == len(v) else None             # u . v

In [31]:
np.dot(u,v)

51

### Vector norm

Again, we could use list comprehension:
    
    norm_u = sum([x**2 for x in u])**0.5
    
but numpy has a built-in method to calculate the norm of a vector:

In [33]:
import numpy.linalg as LA

In [83]:
#norm_u = 
LA.norm(u)

8.6023252670426267

## Matrix math

In [135]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work


### Matrix addition & subtraction

See above rationale for addition and dot product:

In [62]:
#A_plus_C 
print([A+C] if A.shape == C.shape else None)         # A + C

None


I did waste a lot of time writing this list comprehension:

```
A_plus_C = [[A[i,j]+C[i,j] for j in range(A.shape[1])] for i in range(A.shape[0])] \
            if A.shape == C.shape else None
```

In [58]:
#A_minus_Ctranspose = 
A - np.transpose(C)

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [65]:
A - C.T

array([[-4, -7, -3],
       [ 3,  6,  4]])

Again, here is list comprehension code so I don't start crying:

```
A_minus_Ctranspose = [[A[i,j] - np.transpose(C)[i,j] for j in range(A.shape[1])] for i in range(A.shape[0])] \
    if A.shape == np.transpose(C).shape else None  
```

In [52]:
#Ctranspose_plus_3D 
np.transpose(C) + 3*D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [57]:
C.T + 3*D

array([[14,  3,  3],
       [ 2,  7,  9]])

List comprehension / reinventing the wheel:

    Ctranspose_plus_3D = [[D[i,j]*3 + np.transpose(C)[i,j] for j in range(D.shape[1])] for i in range(D.shape[0])] \
        if D.shape == np.transpose(C).shape else None

### Matrix Multiplication
numpy has some built-in methods: 

In [16]:
#B_times_A
np.mat(B) * np.mat(A)

matrix([[-1, -5, -1],
        [ 2,  7,  4]])

equivalent to the dot-product:

In [50]:
np.dot(B,A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [63]:
B.dot(A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

Hey, another list comprehension! which also allows for error checking:

In [140]:
B_times_A = [[sum([B[i,k]*A[k,j] for k in range(A.shape[0])]) for j in range(A.shape[1])] for i in range(B.shape[0])] \
            if B.shape[1] == A.shape[0] else None
print(B_times_A)

[[-1, -5, -1], [2, 7, 4]]


In [45]:
#B_times_Atranspose

Not defined; this code checks for error (shapes don't align)

In [44]:
np.dot(B, np.transpose(A)) if B.shape[1] == np.transpose(A).shape[0] else 'None'

'None'

In [141]:
B_times_Atranspose = [[sum([B[i,k]*A[j,k] for k in range(A.shape[1])]) for j in range(A.shape[0])] \
                      for i in range(B.shape[0])] if B.shape[1] == A.shape[1] else None
print(B_times_Atranspose)

None


In [ ]:
# Q4: (bonus)

In [46]:
B.shape, C.shape

((2, 2), (3, 2))

In [47]:
#B_times_C

In [142]:
B_times_C = [[sum([B[i,k]*C[k,j] for k in range(C.shape[0])]) for j in range(C.shape[1])] for i in range(B.shape[0])] \
            if B.shape[1] == C.shape[0] else None
print(B_times_C)

None


In [48]:
#C_times_B

In [49]:
np.mat(C) * np.mat(B)

matrix([[ 5, -6],
        [ 9, -8],
        [ 6, -6]])

In [64]:
np.dot(C,B)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

In [143]:
C_times_B = [[sum([C[i,k]*B[k,j] for k in range(B.shape[0])]) for j in range(B.shape[1])] for i in range(C.shape[0])] \
            if C.shape[1] == B.shape[0] else None
print(C_times_B)            # C*B

[[5, -6], [9, -8], [6, -6]]


In [66]:
#A_times_Atranspose
np.dot(A, A.T)

array([[14, 28],
       [28, 69]])

In [68]:
A.dot(A.T)

array([[14, 28],
       [28, 69]])

In [67]:
A_times_Atranspose =  [[sum([A[i,k]*A[j,k] for k in range(A.shape[1])]) for j in range(A.shape[0])] \
                       for i in range(A.shape[0])] if A.shape[1] == A.shape[0] else None
print(A_times_Atranspose)  # A*A.T

None


In [173]:
# this is not one of the questions. I was just curious if this actually worked!
B_times_Btranspose =  [[sum([B[i,k]*B[j,k] for k in range(B.shape[1])]) for j in range(B.shape[0])] \
                       for i in range(B.shape[0])] if B.shape[1] == B.shape[0] else None
print(B_times_Btranspose)  # A*A.T

[[2, -1], [-1, 1]]


I got sick of copying & editing code. I know this will evaluate to 'None' because D isn't a square matrix:

In [70]:
#Dtranspose_times_D  # D.T*D

In [71]:
D.T.dot(D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])

In [72]:
np.dot(D.T, D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])

### Matrix power

In [3]:
B

array([[ 1, -1],
       [ 0,  1]])

In [73]:
#B_exp_4 =               # B^4
LA.matrix_power(B, 4)

array([[ 1, -4],
       [ 0,  1]])